# Mod Info
mod_version=1.0.0
mod_group=com.leo
mod_id=stonereverser
mod_name=Stone Reverser

# Minecraft & NeoForge —— 对齐你实际运行的版本
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.248
neo_version_range=[21.1.248, 21.2)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
