modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="stonereverser"
version="1.0.0"
displayName="Stone Reverser"
description="Copper block decomposition and stone reverser block."
authors="leo"

[[dependencies.stonereverser]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.stonereverser]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"